### PR TITLE
finish the AboutComponent and about section

### PR DESCRIPTION
**Pull request by NoorAldeenAbuShehadeh**

### CODE REVIEW

**Comment by YousefMishael** [comment]
Dear Noor,
It's better to create a new folder inside the component called Utils and inside this folder create a Utils file an define the values of cards inside this Utils file then import them to your component. By doing that the readability of your code will be better if you have a lot of cards and you can modify them easily.

BR

**Comment by NoorAldeenAbuShehadeh** [comment]
I am move the data to utils folder and use it inside the my component

**Comment by NoorAldeenAbuShehadeh** [comment]
done

**Review by YousefMishael — APPROVED** [review]
Reviewed and approved

**Pull request merged**
